In [4]:
import pandas as pd
import numpy as np

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\cris\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\cris\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 1.7 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.9 MB 1.8 MB/s eta 0:00:06
   ------ --------------------------------- 1.6/9.9 MB 1.9 MB/s eta 0:00:05
   -------- ------------------------------- 2.1/9.9 MB 2.0 MB/s eta 0:00:04
   ---------- ----------------------------- 2.6/9.9 MB 2.2 MB/s eta 0:00:04
   ------------- -------------------------- 3.4/9.9 MB 2.3 MB/s eta 0:00:03
   --------------- ------------------------ 3.9/9.9 MB 2.4 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.9 MB 2.6 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.9 MB 2.7 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 2.8 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.9 MB 2.8 MB/s eta 0:00:02
   ------------------------------- -------- 7.9/9.9 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 3.2 MB/s  0:00:03
Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 6.4 MB/s eta 0:00:02
   ------- -------------------------------- 2.4/12.6 MB 5.7 MB/s eta 0:00:02
   ----------- ---------------------------- 3.7/12.6 MB 5.8 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.6 MB 6.3 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.6 MB 6.9 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.6 MB 7.5 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 7.9 MB/s  0:00:01
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.1 pandas-3.0.3 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install numpy

Requirement already satisfied: numpy in c:\Users\cris\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.1)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
import numpy as np

In [8]:
import os
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd

enero = pd.read_csv(
    r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes_enero_2026.csv",
    sep=';'
)

febrero = pd.read_csv(
    r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes_febrero_2026.csv",
    sep=';'
)

marzo = pd.read_csv(
    r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes_marzo_2026.csv",
    sep=";",
    low_memory=False
)

abril = pd.read_excel(
    r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes_abril_2026.xlsx"
    
)

mayo = pd.read_excel(
    r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes_mayo_2026.xlsx"
)

In [10]:
print(enero.head())

print(febrero.head())

print(marzo.head())

print(abril.head())

print(mayo.head())

      Fecha   provincia      Canton  Cod_Parroquia  \
0  1/1/2026  CHIMBORAZO    RIOBAMBA        60150.0
1  1/1/2026  CHIMBORAZO  PALLATANGA        60850.0
2  1/1/2026  CHIMBORAZO    RIOBAMBA        60156.0
3  1/1/2026  CHIMBORAZO    RIOBAMBA        60150.0
4  1/1/2026  CHIMBORAZO     CUMANDA        61050.0

                                          Parroquia              Servicio  \
0  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL     Gestión Sanitaria
1                     PALLATANGA, CABECERA CANTONAL     Gestión Sanitaria
2                                             LICTO   Seguridad Ciudadana
3  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL  Tránsito y Movilidad
4                        CUMANDÁ, CABECERA CANTONAL     Gestión Sanitaria

                                       Subtipo
0           Alteración consciencia / lipotimia
1                         Problemas digestivos
2  Patrullaje policial en el sector solicitado
3                                  Vía cerrada
4                    Cefalea - dolor de cabeza
      Fecha provincia       Canton  Cod_Parroquia  \
0  1/2/2026    MANABI   PORTOVIEJO       130150.0
1  1/2/2026    MANABI        MANTA       130850.0
2  1/2/2026    MANABI        MANTA       130850.0
3  1/2/2026    MANABI  MONTECRISTI       130950.0
4  1/2/2026    MANABI  MONTECRISTI       130950.0

                                           Parroquia              Servicio  \
0  PORTOVIEJO, CABECERA CANTONAL Y CAPITAL PROVIN...  Tránsito y Movilidad
1                           MANTA, CABECERA CANTONAL   Seguridad Ciudadana
2                           MANTA, CABECERA CANTONAL   Seguridad Ciudadana
3                     MONTECRISTI, CABECERA CANTONAL   Seguridad Ciudadana
4                     MONTECRISTI, CABECERA CANTONAL   Seguridad Ciudadana

                                             Subtipo
0                                     Estrellamiento
1  Violencia contra la mujer o miembros del núcle...
2        Patrullaje policial en el sector solicitado
3        Patrullaje policial en el sector solicitado
4        Patrullaje policial en el sector solicitado
      Fecha   provincia    Canton  Cod_Parroquia  \
0  1/3/2026  CHIMBORAZO   GUAMOTE        60650.0
1  1/3/2026  CHIMBORAZO    CHAMBO        60450.0
2  1/3/2026  CHIMBORAZO  RIOBAMBA        60150.0
3  1/3/2026  CHIMBORAZO     GUANO        60750.0
4  1/3/2026  CHIMBORAZO   CUMANDA        61050.0

                                          Parroquia              Servicio  \
0                        GUAMOTE, CABECERA CANTONAL  Tránsito y Movilidad
1                         CHAMBO, CABECERA CANTONAL   Seguridad Ciudadana
2  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL  Tránsito y Movilidad
3                          GUANO, CABECERA CANTONAL   Seguridad Ciudadana
4                        CUMANDÁ, CABECERA CANTONAL   Seguridad Ciudadana

                                       Subtipo  Unnamed: 7  Unnamed: 8  \
0                               Procedimientos         NaN         NaN
1                          Fiestas en vivienda         NaN         NaN
2                     Vehículo mal estacionado         NaN         NaN
3  Patrullaje policial en el sector solicitado         NaN         NaN
4  Patrullaje policial en el sector solicitado         NaN         NaN

   Unnamed: 9 Unnamed: 10
0         NaN         NaN
1         NaN         NaN
2         NaN         NaN
3         NaN         NaN
4         NaN         NaN
       Fecha   provincia    Canton  Cod_Parroquia  \
0 2026-04-01  CHIMBORAZO  RIOBAMBA        60150.0
1 2026-04-01  CHIMBORAZO  RIOBAMBA        60150.0
2 2026-04-01  CHIMBORAZO  RIOBAMBA        60150.0
3 2026-04-01  CHIMBORAZO  RIOBAMBA        60150.0
4 2026-04-01  CHIMBORAZO  RIOBAMBA        60150.0

                                          Parroquia              Servicio  \
0  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL   Seguridad Ciudadana
1  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL  Tránsito y Movilidad
2  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL   Seguridad Ciudadana
3  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL   Seguridad Ciudadana
4  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL   Seguridad Ciudadana

                                       Subtipo
0  Patrullaje policial en el sector solicitado
1                           Choque por alcance
2                                    Libadores
3                                    Libadores
4                                    Libadores
       Fecha   provincia      Canton  Cod_Parroquia  \
0 2026-05-01  CHIMBORAZO     GUAMOTE        60652.0
1 2026-05-01  CHIMBORAZO       GUANO        60750.0
2 2026-05-01  CHIMBORAZO    RIOBAMBA        60150.0
3 2026-05-01  CHIMBORAZO    RIOBAMBA        60150.0
4 2026-05-01  CHIMBORAZO  PALLATANGA        60850.0

                                          Parroquia             Servicio  \
0                                           PALMIRA  Seguridad Ciudadana
1                          GUANO, CABECERA CANTONAL  Seguridad Ciudadana
2  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL  Seguridad Ciudadana
3  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL  Seguridad Ciudadana
4                     PALLATANGA, CABECERA CANTONAL    Gestión Sanitaria

                                       Subtipo
0  Patrullaje policial en el sector solicitado
1  Patrullaje policial en el sector solicitado
2                                    Libadores
3                                    Libadores
4     Crisis emocional - trastorno disociativo

In [11]:
print(enero.shape)

print(febrero.shape)

print(marzo.shape)

print(abril.shape)

print(mayo.shape)

(267009, 7)
(250314, 7)
(282649, 11)
(268763, 7)
(290974, 7)

In [12]:
print(enero.columns)

Index(['Fecha', 'provincia', 'Canton', 'Cod_Parroquia', 'Parroquia',
       'Servicio', 'Subtipo'],
      dtype='str')

In [13]:
print(enero.info())

<class 'pandas.DataFrame'>
RangeIndex: 267009 entries, 0 to 267008
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Fecha          267009 non-null  str
 1   provincia      266954 non-null  str
 2   Canton         266954 non-null  str
 3   Cod_Parroquia  266954 non-null  float64
 4   Parroquia      266954 non-null  str
 5   Servicio       267009 non-null  str
 6   Subtipo        267009 non-null  str
dtypes: float64(1), str(6)
memory usage: 14.3 MB
None

In [14]:
enero.isnull().sum()

Fecha             0
provincia        55
Canton           55
Cod_Parroquia    55
Parroquia        55
Servicio          0
Subtipo           0
dtype: int64

In [15]:
print(febrero.info())

<class 'pandas.DataFrame'>
RangeIndex: 250314 entries, 0 to 250313
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Fecha          250314 non-null  str
 1   provincia      250256 non-null  str
 2   Canton         250256 non-null  str
 3   Cod_Parroquia  250256 non-null  float64
 4   Parroquia      250256 non-null  str
 5   Servicio       250287 non-null  str
 6   Subtipo        250287 non-null  str
dtypes: float64(1), str(6)
memory usage: 13.4 MB
None

In [16]:
febrero.isnull().sum()

Fecha             0
provincia        58
Canton           58
Cod_Parroquia    58
Parroquia        58
Servicio         27
Subtipo          27
dtype: int64

In [17]:
print(marzo.info())

<class 'pandas.DataFrame'>
RangeIndex: 282649 entries, 0 to 282648
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Fecha          282649 non-null  str
 1   provincia      282197 non-null  str
 2   Canton         282197 non-null  str
 3   Cod_Parroquia  282197 non-null  float64
 4   Parroquia      282197 non-null  str
 5   Servicio       282649 non-null  str
 6   Subtipo        282649 non-null  str
 7   Unnamed: 7     0 non-null       float64
 8   Unnamed: 8     0 non-null       float64
 9   Unnamed: 9     0 non-null       float64
 10  Unnamed: 10    1 non-null       str
dtypes: float64(4), str(7)
memory usage: 23.7 MB
None

In [18]:
marzo.isnull().sum()

Fecha                 0
provincia           452
Canton              452
Cod_Parroquia       452
Parroquia           452
Servicio              0
Subtipo               0
Unnamed: 7       282649
Unnamed: 8       282649
Unnamed: 9       282649
Unnamed: 10      282648
dtype: int64

In [19]:
print(abril.info())

<class 'pandas.DataFrame'>
RangeIndex: 268763 entries, 0 to 268762
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Fecha          268763 non-null  datetime64[us]
 1   provincia      268697 non-null  str
 2   Canton         268697 non-null  str
 3   Cod_Parroquia  268697 non-null  float64
 4   Parroquia      268697 non-null  str
 5   Servicio       268763 non-null  str
 6   Subtipo        268763 non-null  str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 14.4 MB
None

In [20]:
abril.isnull().sum()

Fecha             0
provincia        66
Canton           66
Cod_Parroquia    66
Parroquia        66
Servicio          0
Subtipo           0
dtype: int64

In [21]:
enero.describe(include="all")

,Fecha,provincia,Canton,Cod_Parroquia,Parroquia,Servicio,Subtipo
count,267009,266954,266954,266954.000000,266954,267009,267009
unique,31,25,222,NaN,939,7,521
top,1/1/2026,GUAYAS,QUITO,NaN,"GUAYAQUIL, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Seguridad Ciudadana,Patrullaje policial en el sector solicitado
freq,14736,64475,56752,NaN,46432,179137,65162
mean,NaN,NaN,NaN,120858.047937,NaN,NaN,NaN
std,NaN,NaN,NaN,57959.767282,NaN,NaN,NaN
min,NaN,NaN,NaN,10150.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,90150.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,110150.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,170150.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,900451.000000,NaN,NaN,NaN

In [22]:
febrero.describe(include="all")

,Fecha,provincia,Canton,Cod_Parroquia,Parroquia,Servicio,Subtipo
count,250314,250256,250256,250256.000000,250256,250287,250287
unique,28,25,222,NaN,930,7,524
top,15/2/2026,PICHINCHA,QUITO,NaN,"GUAYAQUIL, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Seguridad Ciudadana,Patrullaje policial en el sector solicitado
freq,11716,59623,52946,NaN,42529,168125,62345
mean,NaN,NaN,NaN,120972.140137,NaN,NaN,NaN
std,NaN,NaN,NaN,58339.753182,NaN,NaN,NaN
min,NaN,NaN,NaN,10150.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,90150.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,110150.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,170150.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,900451.000000,NaN,NaN,NaN

In [23]:
marzo.describe(include="all")

,Fecha,provincia,Canton,Cod_Parroquia,Parroquia,Servicio,Subtipo,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
count,282649,282197,282197,282197.000000,282197,282649,282649,0.0,0.0,0.0,1
unique,31,25,222,NaN,937,7,529,NaN,NaN,NaN,1
top,15/3/2026,GUAYAS,QUITO,NaN,"GUAYAQUIL, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Seguridad Ciudadana,Patrullaje policial en el sector solicitado,NaN,NaN,NaN,
freq,11552,67833,60326,NaN,49410,190601,72082,NaN,NaN,NaN,1
mean,NaN,NaN,NaN,121484.500735,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,57949.260436,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,10150.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,90150.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,110150.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,170150.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,900451.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
abril.describe(include="all")

,Fecha,provincia,Canton,Cod_Parroquia,Parroquia,Servicio,Subtipo
count,268763,268697,268697,268697.000000,268697,268763,268763
unique,NaN,25,222,NaN,940,7,534
top,NaN,PICHINCHA,QUITO,NaN,"GUAYAQUIL, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Seguridad Ciudadana,Patrullaje policial en el sector solicitado
freq,NaN,66446,59388,NaN,46671,182201,65783
mean,2026-04-15 12:09:55.206929,NaN,NaN,121726.178435,NaN,NaN,NaN
min,2026-04-01 00:00:00,NaN,NaN,10150.000000,NaN,NaN,NaN
25%,2026-04-08 00:00:00,NaN,NaN,90150.000000,NaN,NaN,NaN
50%,2026-04-16 00:00:00,NaN,NaN,110250.000000,NaN,NaN,NaN
75%,2026-04-23 00:00:00,NaN,NaN,170150.000000,NaN,NaN,NaN
max,2026-04-30 00:00:00,NaN,NaN,900451.000000,NaN,NaN,NaN
std,NaN,NaN,NaN,58332.024541,NaN,NaN,NaN

In [25]:
mayo.describe(include="all")

,Fecha,provincia,Canton,Cod_Parroquia,Parroquia,Servicio,Subtipo
count,290974,290918,290918,290918.000000,290918,290970,290970
unique,NaN,25,222,NaN,942,7,533
top,NaN,GUAYAS,QUITO,NaN,"GUAYAQUIL, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Seguridad Ciudadana,Patrullaje policial en el sector solicitado
freq,NaN,70301,61758,NaN,52676,194448,71609
mean,2026-05-16 05:34:47.864894,NaN,NaN,120505.151675,NaN,NaN,NaN
min,2026-05-01 00:00:00,NaN,NaN,10150.000000,NaN,NaN,NaN
25%,2026-05-09 00:00:00,NaN,NaN,90150.000000,NaN,NaN,NaN
50%,2026-05-16 00:00:00,NaN,NaN,110150.000000,NaN,NaN,NaN
75%,2026-05-24 00:00:00,NaN,NaN,170150.000000,NaN,NaN,NaN
max,2026-05-31 00:00:00,NaN,NaN,900451.000000,NaN,NaN,NaN
std,NaN,NaN,NaN,58030.641158,NaN,NaN,NaN

In [26]:
print("Enero:", len(enero))
print("Febrero:", len(febrero))
print("Marzo:", len(marzo))
print("Abril:", len(abril))
print("Mayo:", len(mayo))

Enero: 267009
Febrero: 250314
Marzo: 282649
Abril: 268763
Mayo: 290974

In [27]:
print("Duplicados Enero:", enero.duplicated().sum())
print("Duplicados Febrero:", febrero.duplicated().sum())
print("Duplicados Marzo:", marzo.duplicated().sum())
print("Duplicados Abril:", abril.duplicated().sum())
print("Duplicados Mayo:", mayo.duplicated().sum())

Duplicados Enero: 172400
Duplicados Febrero: 161965
Duplicados Marzo: 184471
Duplicados Abril: 175836
Duplicados Mayo: 191261

In [28]:
print(enero.isnull().sum())
print(febrero.isnull().sum())
print(marzo.isnull().sum())
print(abril.isnull().sum())
print(mayo.isnull().sum())

Fecha             0
provincia        55
Canton           55
Cod_Parroquia    55
Parroquia        55
Servicio          0
Subtipo           0
dtype: int64
Fecha             0
provincia        58
Canton           58
Cod_Parroquia    58
Parroquia        58
Servicio         27
Subtipo          27
dtype: int64
Fecha                 0
provincia           452
Canton              452
Cod_Parroquia       452
Parroquia           452
Servicio              0
Subtipo               0
Unnamed: 7       282649
Unnamed: 8       282649
Unnamed: 9       282649
Unnamed: 10      282648
dtype: int64
Fecha             0
provincia        66
Canton           66
Cod_Parroquia    66
Parroquia        66
Servicio          0
Subtipo           0
dtype: int64
Fecha             0
provincia        56
Canton           56
Cod_Parroquia    56
Parroquia        56
Servicio          4
Subtipo           4
dtype: int64

In [29]:
print(enero.dtypes)

Fecha                str
provincia            str
Canton               str
Cod_Parroquia    float64
Parroquia            str
Servicio             str
Subtipo              str
dtype: object

In [30]:
print(febrero.dtypes)

Fecha                str
provincia            str
Canton               str
Cod_Parroquia    float64
Parroquia            str
Servicio             str
Subtipo              str
dtype: object

In [31]:
print(marzo.dtypes)

Fecha                str
provincia            str
Canton               str
Cod_Parroquia    float64
Parroquia            str
Servicio             str
Subtipo              str
Unnamed: 7       float64
Unnamed: 8       float64
Unnamed: 9       float64
Unnamed: 10          str
dtype: object

In [32]:
print(abril.dtypes)

Fecha            datetime64[us]
provincia                   str
Canton                      str
Cod_Parroquia           float64
Parroquia                   str
Servicio                    str
Subtipo                     str
dtype: object

In [33]:
print(mayo.dtypes)

Fecha            datetime64[us]
provincia                   str
Canton                      str
Cod_Parroquia           float64
Parroquia                   str
Servicio                    str
Subtipo                     str
dtype: object

In [34]:
enero["provincia"].value_counts()

provincia
GUAYAS                            64475
PICHINCHA                         63868
AZUAY                             15777
MANABI                            12432
TUNGURAHUA                        11863
LOS RIOS                          10571
IMBABURA                          10248
EL ORO                            10185
SANTO DOMINGO DE LOS TSACHILAS     8785
CHIMBORAZO                         7591
LOJA                               7480
ESMERALDAS                         6634
COTOPAXI                           6537
SUCUMBIOS                          4644
SANTA ELENA                        4318
MORONA SANTIAGO                    4073
CARCHI                             3406
BOLIVAR                            3009
CAÑAR                              2645
ORELLANA                           2327
PASTAZA                            1989
ZAMORA CHINCHIPE                   1667
NAPO                               1464
GALAPAGOS                           929
ZONA NO DELIMITADA                   37
Name: count, dtype: int64

In [35]:
datos = pd.concat(
    [enero, febrero, marzo, abril, mayo],
    ignore_index=True
)

In [36]:
datos.shape

(1359709, 11)

In [39]:
datos.to_csv(
    r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\scripts\Total_incidentes\Total_incidentes\incidentes_total.csv",
    index=False
)

In [40]:
datos.head(10)

,Fecha,provincia,Canton,Cod_Parroquia,Parroquia,Servicio,Subtipo,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1/1/2026,CHIMBORAZO,RIOBAMBA,60150.0,"RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Gestión Sanitaria,Alteración consciencia / lipotimia,NaN,NaN,NaN,NaN
1,1/1/2026,CHIMBORAZO,PALLATANGA,60850.0,"PALLATANGA, CABECERA CANTONAL",Gestión Sanitaria,Problemas digestivos,NaN,NaN,NaN,NaN
2,1/1/2026,CHIMBORAZO,RIOBAMBA,60156.0,LICTO,Seguridad Ciudadana,Patrullaje policial en el sector solicitado,NaN,NaN,NaN,NaN
3,1/1/2026,CHIMBORAZO,RIOBAMBA,60150.0,"RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Tránsito y Movilidad,Vía cerrada,NaN,NaN,NaN,NaN
4,1/1/2026,CHIMBORAZO,CUMANDA,61050.0,"CUMANDÁ, CABECERA CANTONAL",Gestión Sanitaria,Cefalea - dolor de cabeza,NaN,NaN,NaN,NaN
5,1/1/2026,CHIMBORAZO,GUAMOTE,60652.0,PALMIRA,Gestión Sanitaria,Quemaduras,NaN,NaN,NaN,NaN
6,1/1/2026,CHIMBORAZO,RIOBAMBA,60150.0,"RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Seguridad Ciudadana,Patrullaje policial en el sector solicitado,NaN,NaN,NaN,NaN
7,1/1/2026,CHIMBORAZO,RIOBAMBA,60150.0,"RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Gestión Sanitaria,Paro cardiaco,NaN,NaN,NaN,NaN
8,1/1/2026,CHIMBORAZO,GUAMOTE,60650.0,"GUAMOTE, CABECERA CANTONAL",Seguridad Ciudadana,Violación,NaN,NaN,NaN,NaN
9,1/1/2026,CHIMBORAZO,RIOBAMBA,60150.0,"RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Tránsito y Movilidad,Procedimientos,NaN,NaN,NaN,NaN

In [41]:
datos[['Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 10']].head(20)

    Unnamed: 7  Unnamed: 8  Unnamed: 9 Unnamed: 10
0          NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN
2          NaN         NaN         NaN         NaN
3          NaN         NaN         NaN         NaN
4          NaN         NaN         NaN         NaN
5          NaN         NaN         NaN         NaN
6          NaN         NaN         NaN         NaN
7          NaN         NaN         NaN         NaN
8          NaN         NaN         NaN         NaN
9          NaN         NaN         NaN         NaN
10         NaN         NaN         NaN         NaN
11         NaN         NaN         NaN         NaN
12         NaN         NaN         NaN         NaN
13         NaN         NaN         NaN         NaN
14         NaN         NaN         NaN         NaN
15         NaN         NaN         NaN         NaN
16         NaN         NaN         NaN         NaN
17         NaN         NaN         NaN         NaN
18         NaN         NaN         NaN         NaN
19         NaN         NaN         NaN         NaN

In [42]:
datos[['Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 10']].count()

Unnamed: 7     0
Unnamed: 8     0
Unnamed: 9     0
Unnamed: 10    1
dtype: int64

In [43]:
datos = datos.drop(columns=[
    'Unnamed: 7',
    'Unnamed: 8',
    'Unnamed: 9',
    'Unnamed: 10'
])

In [44]:
datos.columns

Index(['Fecha', 'provincia', 'Canton', 'Cod_Parroquia', 'Parroquia',
       'Servicio', 'Subtipo'],
      dtype='str')

In [45]:
datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 1359709 entries, 0 to 1359708
Data columns (total 7 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Fecha          1359709 non-null  object
 1   provincia      1359022 non-null  str
 2   Canton         1359022 non-null  str
 3   Cod_Parroquia  1359022 non-null  float64
 4   Parroquia      1359022 non-null  str
 5   Servicio       1359678 non-null  str
 6   Subtipo        1359678 non-null  str
dtypes: float64(1), object(1), str(5)
memory usage: 72.6+ MB

In [46]:
datos.isnull().sum()

Fecha              0
provincia        687
Canton           687
Cod_Parroquia    687
Parroquia        687
Servicio          31
Subtipo           31
dtype: int64

In [47]:
datos.shape

(1359709, 7)

In [48]:
datos_limpios = datos.copy()

In [49]:
print(datos_limpios.columns)

Index(['Fecha', 'provincia', 'Canton', 'Cod_Parroquia', 'Parroquia',
       'Servicio', 'Subtipo'],
      dtype='str')

In [50]:
datos_limpios.isnull().sum()

Fecha              0
provincia        687
Canton           687
Cod_Parroquia    687
Parroquia        687
Servicio          31
Subtipo           31
dtype: int64

In [51]:
datos_limpios = datos_limpios.dropna()

In [52]:
datos_limpios.isnull().sum()

Fecha            0
provincia        0
Canton           0
Cod_Parroquia    0
Parroquia        0
Servicio         0
Subtipo          0
dtype: int64

In [53]:
print("Antes:", len(datos_limpios))

datos_limpios = datos_limpios.drop_duplicates()

print("Después:", len(datos_limpios))

Antes: 1358995
Después: 473394

In [54]:
columnas_texto = [
    "provincia",
    "Canton",
    "Parroquia",
    "Servicio",
    "Subtipo"
]

for columna in columnas_texto:
    datos_limpios[columna] = datos_limpios[columna].astype(str).str.strip()

In [55]:
datos_limpios["Fecha"].head(10)

0    1/1/2026
1    1/1/2026
2    1/1/2026
3    1/1/2026
4    1/1/2026
5    1/1/2026
6    1/1/2026
7    1/1/2026
8    1/1/2026
9    1/1/2026
Name: Fecha, dtype: object

In [56]:
datos_limpios.info()

<class 'pandas.DataFrame'>
Index: 473394 entries, 0 to 1359707
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Fecha          473394 non-null  object
 1   provincia      473394 non-null  str
 2   Canton         473394 non-null  str
 3   Cod_Parroquia  473394 non-null  float64
 4   Parroquia      473394 non-null  str
 5   Servicio       473394 non-null  str
 6   Subtipo        473394 non-null  str
dtypes: float64(1), object(1), str(5)
memory usage: 28.9+ MB

In [57]:
datos_limpios["Fecha"] = pd.to_datetime(
    datos_limpios["Fecha"],
    format="%d/%m/%Y"
)

In [58]:
datos_limpios.info()

<class 'pandas.DataFrame'>
Index: 473394 entries, 0 to 1359707
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Fecha          473394 non-null  datetime64[us]
 1   provincia      473394 non-null  str
 2   Canton         473394 non-null  str
 3   Cod_Parroquia  473394 non-null  float64
 4   Parroquia      473394 non-null  str
 5   Servicio       473394 non-null  str
 6   Subtipo        473394 non-null  str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 28.9 MB

In [59]:
datos_limpios.head()

,Fecha,provincia,Canton,Cod_Parroquia,Parroquia,Servicio,Subtipo
0,2026-01-01,CHIMBORAZO,RIOBAMBA,60150.0,"RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Gestión Sanitaria,Alteración consciencia / lipotimia
1,2026-01-01,CHIMBORAZO,PALLATANGA,60850.0,"PALLATANGA, CABECERA CANTONAL",Gestión Sanitaria,Problemas digestivos
2,2026-01-01,CHIMBORAZO,RIOBAMBA,60156.0,LICTO,Seguridad Ciudadana,Patrullaje policial en el sector solicitado
3,2026-01-01,CHIMBORAZO,RIOBAMBA,60150.0,"RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Tránsito y Movilidad,Vía cerrada
4,2026-01-01,CHIMBORAZO,CUMANDA,61050.0,"CUMANDÁ, CABECERA CANTONAL",Gestión Sanitaria,Cefalea - dolor de cabeza

In [62]:
datos_limpios.to_csv(
    r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\scripts\Total_incidentes\Total_incidentes\incidentes_limpios.csv",
    index=False
)

In [64]:
import pandas as pd

# Leer archivo limpio
datos = pd.read_csv(r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\scripts\Total_incidentes\Total_incidentes\incidentes_limpios.csv")

# Mostrar información general
print("=" * 50)
print("INFORMACIÓN DEL DATASET")
print("=" * 50)

print("Número de registros:", len(datos))
print("Número de columnas:", len(datos.columns))

print("\nColumnas:")
print(datos.columns.tolist())

print("\nTipos de datos:")
print(datos.dtypes)

print("\nPrimeras filas:")
print(datos.head())

print("\nValores nulos:")
print(datos.isnull().sum())

==================================================
INFORMACIÓN DEL DATASET
==================================================
Número de registros: 473394
Número de columnas: 7

Columnas:
['Fecha', 'provincia', 'Canton', 'Cod_Parroquia', 'Parroquia', 'Servicio', 'Subtipo']

Tipos de datos:
Fecha                str
provincia            str
Canton               str
Cod_Parroquia    float64
Parroquia            str
Servicio             str
Subtipo              str
dtype: object

Primeras filas:
        Fecha   provincia      Canton  Cod_Parroquia  \
0  2026-01-01  CHIMBORAZO    RIOBAMBA        60150.0
1  2026-01-01  CHIMBORAZO  PALLATANGA        60850.0
2  2026-01-01  CHIMBORAZO    RIOBAMBA        60156.0
3  2026-01-01  CHIMBORAZO    RIOBAMBA        60150.0
4  2026-01-01  CHIMBORAZO     CUMANDA        61050.0

                                          Parroquia              Servicio  \
0  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL     Gestión Sanitaria
1                     PALLATANGA, CABECERA CANTONAL     Gestión Sanitaria
2                                             LICTO   Seguridad Ciudadana
3  RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL  Tránsito y Movilidad
4                        CUMANDÁ, CABECERA CANTONAL     Gestión Sanitaria

                                       Subtipo
0           Alteración consciencia / lipotimia
1                         Problemas digestivos
2  Patrullaje policial en el sector solicitado
3                                  Vía cerrada
4                    Cefalea - dolor de cabeza

Valores nulos:
Fecha            0
provincia        0
Canton           0
Cod_Parroquia    0
Parroquia        0
Servicio         0
Subtipo          0
dtype: int64

In [70]:
import os
import sqlite3
import pandas as pd

# 1. Definir la ruta del archivo de base de datos
db_path = r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes.db"

os.makedirs(os.path.dirname(db_path), exist_ok=True)
# Conectar (SQLite creará el archivo automáticamente en esa carpeta)
conn = sqlite3.connect(db_path)
print("¡Conexión establecida con éxito!")

# 2. Configurar la lista de tus archivos
archivos = [
    {
        "mes": "enero",
        "tipo": "csv",
        "path": r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes_enero_2026.csv",
        "sep": ";",
    },
    {
        "mes": "febrero",
        "tipo": "csv",
        "path": r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes_febrero_2026.csv",
        "sep": ";",
    },
    {
        "mes": "marzo",
        "tipo": "csv",
        "path": r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes_marzo_2026.csv",
        "sep": ";",
    },
    {
        "mes": "abril",
        "tipo": "excel",
        "path": r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes_abril_2026.xlsx",
    },
    {
        "mes": "mayo",
        "tipo": "excel",
        "path": r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes_mayo_2026.xlsx",
    },
]

columnas_validas = [
    "Fecha",
    "provincia",
    "Canton",
    "Cod_Parroquia",
    "Parroquia",
    "Servicio",
    "Subtipo",
]

# 3. Insertar datos mes por mes en la tabla 'incidentes'
for item in archivos:
    print(f"Cargando {item['mes']} a SQLite...")

    if item["tipo"] == "csv":
        df = pd.read_csv(item["path"], sep=item["sep"], low_memory=False)
    else:
        df = pd.read_excel(item["path"])

    # Limpiar columnas extra (como las del mes de marzo)
    df = df[[col for col in columnas_validas if col in df.columns]]

    # Formatear la fecha
    df["Fecha"] = pd.to_datetime(df["Fecha"], errors="coerce").dt.strftime(
        "%Y-%m-%d"
    )

    # Insertar en SQLite
    df.to_sql("incidentes", conn, if_exists="append", index=False)

print("¡Consolidación en SQLite realizada con éxito!")

¡Conexión establecida con éxito!
Cargando enero a SQLite...
Cargando febrero a SQLite...
Cargando marzo a SQLite...
Cargando abril a SQLite...
Cargando mayo a SQLite...
¡Consolidación en SQLite realizada con éxito!

In [71]:
# Comprobar la cantidad total de registros en SQLite
df_total = pd.read_sql_query("SELECT COUNT(*) AS Total_Registros FROM incidentes;", conn)
print("Total de registros cargados en SQLite:")
print(df_total)

# Ver una muestra de las primeras 5 filas
df_muestra = pd.read_sql_query("SELECT * FROM incidentes LIMIT 5;", conn)
df_muestra

Total de registros cargados en SQLite:
   Total_Registros
0          1359709

,Fecha,provincia,Canton,Cod_Parroquia,Parroquia,Servicio,Subtipo
0,2026-01-01,CHIMBORAZO,RIOBAMBA,60150.0,"RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Gestión Sanitaria,Alteración consciencia / lipotimia
1,2026-01-01,CHIMBORAZO,PALLATANGA,60850.0,"PALLATANGA, CABECERA CANTONAL",Gestión Sanitaria,Problemas digestivos
2,2026-01-01,CHIMBORAZO,RIOBAMBA,60156.0,LICTO,Seguridad Ciudadana,Patrullaje policial en el sector solicitado
3,2026-01-01,CHIMBORAZO,RIOBAMBA,60150.0,"RIOBAMBA, CABECERA CANTONAL Y CAPITAL PROVINCIAL",Tránsito y Movilidad,Vía cerrada
4,2026-01-01,CHIMBORAZO,CUMANDA,61050.0,"CUMANDÁ, CABECERA CANTONAL",Gestión Sanitaria,Cefalea - dolor de cabeza

In [74]:
import json

json_path = r"datos\incidentes_nosql.json"

print("Exportando datos a formato JSON (NoSQL)...")

# Cargar todos los datos de SQLite a pandas
df_completo = pd.read_sql_query("SELECT * FROM incidentes;", conn)

# Exportar a JSON en formato de lista de documentos 
df_completo.to_json(
    r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes_nosql.jsonl", orient="records", lines=True
)

print(f"¡Exportación NoSQL completada exitosamente en: {json_path}!")

Exportando datos a formato JSON (NoSQL)...
¡Exportación NoSQL completada exitosamente en: datos\incidentes_nosql.json!

In [75]:
# 1. Incidentes por Provincia (Top 10)
df_provincias = pd.read_sql_query("""
    SELECT provincia, COUNT(*) as Total
    FROM incidentes
    GROUP BY provincia
    ORDER BY Total DESC
    LIMIT 10;
""", conn)

print("--- TOP 10 PROVINCIAS ---")
print(df_provincias)

# 2. Incidentes por Tipo de Servicio
df_servicios = pd.read_sql_query("""
    SELECT Servicio, COUNT(*) as Total
    FROM incidentes
    GROUP BY Servicio
    ORDER BY Total DESC;
""", conn)

print("\n--- INCIDENTES POR SERVICIO ---")
print(df_servicios)

# Cerrar la conexión cuando termines todo el proceso
conn.close()

--- TOP 10 PROVINCIAS ---
                        provincia   Total
0                       PICHINCHA  327065
1                          GUAYAS  325285
2                           AZUAY   79293
3                          MANABI   63076
4                      TUNGURAHUA   60513
5                        LOS RIOS   54502
6                          EL ORO   52158
7                        IMBABURA   51625
8  SANTO DOMINGO DE LOS TSACHILAS   45624
9                      CHIMBORAZO   38221

--- INCIDENTES POR SERVICIO ---
                Servicio   Total
0    Seguridad Ciudadana  914512
1      Gestión Sanitaria  170561
2   Tránsito y Movilidad  161794
3  Servicios Municipales   55219
4       Servicio Militar   28568
5  Gestión de Siniestros   22873
6     Gestión de Riesgos    6151
7                    NaN      31

In [76]:
%pip install pymongo

Collecting pymongo
  Downloading pymongo-4.17.0-cp314-cp314-win_amd64.whl.metadata (10 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.17.0-cp314-cp314-win_amd64.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/1.0 MB 4.1 MB/s  0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
Installing collected packages: dnspython, pymongo

   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   ---------------------------------------- 2/2 [pymongo]

Successfully installed dnspython-2.8.0 pymongo-4.17.0
Note: you may need to restart the kernel to use updated packages.

In [78]:
import sqlite3
import pandas as pd
from pymongo import MongoClient

# 1. Reabrir la conexión a tu base de datos SQLite
conn = sqlite3.connect(r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes.db")

# 2. Cadena de Conexión a MongoDB (Local)
connection_string = "mongodb://localhost:27017/"
client = MongoClient(connection_string)

# Crear / Seleccionar la Base de Datos y la Colección
db = client["ecu911_db"]
collection = db["incidentes"]

# 3. Leer los datos consolidados desde SQLite
df_completo = pd.read_sql_query("SELECT * FROM incidentes;", conn)

# 4. Convertir el DataFrame a formato de Diccionario (Documentos NoSQL)
documentos = df_completo.to_dict(orient="records")

# 5. Insertar por Lotes (Batch/Chunks)
tamanio_lote = 50000
total_documentos = len(documentos)

print(f"Insertando {total_documentos} documentos en MongoDB...")

# Limpiar la colección si ya tenía datos previos
collection.delete_many({})

for i in range(0, total_documentos, tamanio_lote):
    lote = documentos[i : i + tamanio_lote]
    collection.insert_many(lote)
    print(
        f"Lote insertado: {min(i + tamanio_lote, total_documentos)} / {total_documentos}"
    )

print("\n¡Carga a MongoDB completada exitosamente!")

# Cerrar conexión de SQLite al finalizar
conn.close()

Insertando 1359709 documentos en MongoDB...
Lote insertado: 50000 / 1359709
Lote insertado: 100000 / 1359709
Lote insertado: 150000 / 1359709
Lote insertado: 200000 / 1359709
Lote insertado: 250000 / 1359709
Lote insertado: 300000 / 1359709
Lote insertado: 350000 / 1359709
Lote insertado: 400000 / 1359709
Lote insertado: 450000 / 1359709
Lote insertado: 500000 / 1359709
Lote insertado: 550000 / 1359709
Lote insertado: 600000 / 1359709
Lote insertado: 650000 / 1359709
Lote insertado: 700000 / 1359709
Lote insertado: 750000 / 1359709
Lote insertado: 800000 / 1359709
Lote insertado: 850000 / 1359709
Lote insertado: 900000 / 1359709
Lote insertado: 950000 / 1359709
Lote insertado: 1000000 / 1359709
Lote insertado: 1050000 / 1359709
Lote insertado: 1100000 / 1359709
Lote insertado: 1150000 / 1359709
Lote insertado: 1200000 / 1359709
Lote insertado: 1250000 / 1359709
Lote insertado: 1300000 / 1359709
Lote insertado: 1350000 / 1359709
Lote insertado: 1359709 / 1359709

¡Carga a MongoDB completada exitosamente!

In [106]:
import sqlite3
import pandas as pd
from pymongo import MongoClient

# 1. Conectar a SQLite y leer todo el dataset de +2M
conn = sqlite3.connect(r"C:\Users\cris\Desktop\Veliz_Sanchez_ProyectoFinalAnalisis\datos\incidentes.db")
print("Cargando los 2M de registros desde SQLite...")
df_completo = pd.read_sql_query("SELECT * FROM incidentes;", conn)
conn.close()

# 2. Conectar a MongoDB
client = MongoClient("mongodb://localhost:27017/")
db = client["ecu911_db"]
collection = db["incidentes"]

# 3. Limpiar colección previa e insertar en lotes
print("Limpiando colección anterior en MongoDB...")
collection.delete_many({})

print("Insertando documentos en MongoDB por lotes...")
documentos = df_completo.to_dict(orient="records")

tamanio_lote = 100000
total_docs = len(documentos)

for i in range(0, total_docs, tamanio_lote):
    lote = documentos[i : i + tamanio_lote]
    collection.insert_many(lote)
    print(f"Progreso: {min(i + tamanio_lote, total_docs):,} / {total_docs:,}")

print("\n¡Proceso finalizado con éxito en MongoDB!")

Cargando los 2M de registros desde SQLite...
Limpiando colección anterior en MongoDB...
Insertando documentos en MongoDB por lotes...
Progreso: 100,000 / 2,300,000
Progreso: 200,000 / 2,300,000
Progreso: 300,000 / 2,300,000
Progreso: 400,000 / 2,300,000
Progreso: 500,000 / 2,300,000
Progreso: 600,000 / 2,300,000
Progreso: 700,000 / 2,300,000
Progreso: 800,000 / 2,300,000
Progreso: 900,000 / 2,300,000
Progreso: 1,000,000 / 2,300,000
Progreso: 1,100,000 / 2,300,000
Progreso: 1,200,000 / 2,300,000
Progreso: 1,300,000 / 2,300,000
Progreso: 1,400,000 / 2,300,000
Progreso: 1,500,000 / 2,300,000
Progreso: 1,600,000 / 2,300,000
Progreso: 1,700,000 / 2,300,000
Progreso: 1,800,000 / 2,300,000
Progreso: 1,900,000 / 2,300,000
Progreso: 2,000,000 / 2,300,000
Progreso: 2,100,000 / 2,300,000
Progreso: 2,200,000 / 2,300,000
Progreso: 2,300,000 / 2,300,000

¡Proceso finalizado con éxito en MongoDB!

In [109]:
import os
import random
import sqlite3
import pandas as pd

# 1. Rutas
db_path = "incidentes.db"
csv_ficticios_path = "incidentes_ficticios.csv"

# 2. Conectar a SQLite
conn = sqlite3.connect(db_path)

# Queremos generar exactamente la cuota ficticia necesaria
CANTIDAD_FICTICIOS = 1850000

print(
    f"Generando {CANTIDAD_FICTICIOS:,} registros ficticios obligatoriamente..."
)

# Tomar muestra de la BD actual para mantener nombres de columnas y categorías reales
df_base = pd.read_sql_query("SELECT * FROM incidentes LIMIT 100000;", conn)

# Muestreo aleatorio
df_ficticios = df_base.sample(n=CANTIDAD_FICTICIOS, replace=True).copy()

# Generar variabilidad de fechas sintéticas
fechas_posibles = pd.date_range(
    start="2026-01-01", end="2026-06-30", freq="s"
)
df_ficticios["Fecha"] = [
    random.choice(fechas_posibles).strftime("%Y-%m-%d %H:%M:%S")
    for _ in range(CANTIDAD_FICTICIOS)
]

# 3. GUARDAR EL ARCHIVO CSV
df_ficticios.to_csv(csv_ficticios_path, index=False, encoding="utf-8")

print("\n" + "=" * 50)
print("¡ARCHIVO CREADO CORRECTAMENTE!")
print(f"Nombre del archivo: {csv_ficticios_path}")
print(f"Filas guardadas en CSV: {len(df_ficticios):,}")
print("=" * 50)

conn.close()

Generando 1,850,000 registros ficticios obligatoriamente...

==================================================
¡ARCHIVO CREADO CORRECTAMENTE!
Nombre del archivo: incidentes_ficticios.csv
Filas guardadas en CSV: 1,850,000
==================================================

In [104]:
import os
import random
import sqlite3
import pandas as pd

# 1. Conexión y Meta
db_path = "incidentes.db"
archivo_ficticios = "incidentes_ficticios.csv"
META_TOTAL = 2300000

print("Conectando a la base de datos sqlite...")
conn = sqlite3.connect(db_path)

# 2. Obtener el total de registros limpios en la BD
total_reales = pd.read_sql_query(
    "SELECT COUNT(*) AS total FROM incidentes;", conn
)["total"].iloc[0]
faltantes = META_TOTAL - total_reales

print("\n" + "=" * 50)
print(f"Registros reales en BD:  {total_reales:,}")
print(f"Meta total requerida:   {META_TOTAL:,}")
print(f"Ficticios a generar:    {faltantes:,}")
print("=" * 50 + "\n")

if faltantes > 0:
    print("Cargando muestra base para generar los datos ficticios...")
    df_base = pd.read_sql_query("SELECT * FROM incidentes LIMIT 50000;", conn)

    # Muestreo aleatorio masivo para la diferencia exactas
    df_ficticios = df_base.sample(n=faltantes, replace=True).copy()

    # Aleatorizar fechas para dar variabilidad
    fechas_posibles = pd.date_range(
        start="2026-01-01", end="2026-06-30", freq="s"
    )
    df_ficticios["Fecha"] = [
        random.choice(fechas_posibles).strftime("%Y-%m-%d %H:%M:%S")
        for _ in range(faltantes)
    ]

    # Sobrescribir directamente el CSV
    print(f"Generando y sobrescribiendo '{archivo_ficticios}'...")
    df_ficticios.to_csv(archivo_ficticios, index=False, encoding="utf-8")

    print("\n" + "¡PROCESO COMPLETADO EXITOSAMENTE! " + "✔" * 3)
    print(
        f"El archivo '{archivo_ficticios}' ahora tiene exactamente {len(df_ficticios):,} filas."
    )
else:
    print("Tus datos reales ya alcanzan o superan la meta.")

conn.close()

Conectando a la base de datos sqlite...

==================================================
Registros reales en BD:  2,300,000
Meta total requerida:   2,300,000
Ficticios a generar:    0
==================================================

Tus datos reales ya alcanzan o superan la meta.